### ISSUE TITLE
Counting models don't predict location

### ISSUE THREAD

**Issue by bentocg** [iceberg-project/Seals#19]
Create a new pipeline that counts and detects the location of each seal

**Comment by iparask** [comment]
Hey @bentocg , we set up with Brad a milestone to be able to analyze the whole dataset from last year until mid December. Do you think that this is relevant and should be included there?

**Comment by bentocg** [comment]
Hi @iparask , that is relevant and doable, @bspitzbart is finishing training, we might be able to set this up tomorrow.
