### ISSUE TITLE
Scale up to about 4500 images

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#21]
Execute the Seals Use Case script with the whole image dataset from last year.

**Comment by bspitzbart** [comment]
Distribution of file sizes (total of 4357 images)
[2017seals_list.txt](https://github.com/iceberg-project/Seals/files/2362357/2017seals_list.txt)
![image](https://user-images.githubusercontent.com/1823451/45240847-13c1e180-b2b8-11e8-9fe8-5bef7ee95b40.png)

**Comment by iparask** [comment]
Thank you Brat! Here is a more detailed histogram: http://js-157-203.jetstream-cloud.org:9999/notebooks/ICEBERG/fulldataset/SealsWholeDatasetFilesizeHistogram.ipynb

**Comment by iparask** [comment]
Hello Brad,

Can I get images with the following sizes?

- [x] 128MBs
- [x] 256MBs
- [x] 512MBs
- [x] 1024MBs
- [x] 2048MBs and 
- [x] 2560MBs

I would like to do a quick profiling of all the stages based on these image sizes. Thank you!

**Comment by bspitzbart** [comment]
There are data with those approximate sizes at:
/pylon5/mc3bggp/bspitz/Scale

**Comment by iparask** [comment]
I have executed a run with 3096 images. Brad has the results

**Comment by iparask** [comment]
When #46 is fixed and everything is merged back to devel we can consider this closed
