### ISSUE TITLE
MyProxy does not create credentials

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#23]
From @bspitzbart :

The gsissh and myproxy installation needs clarification. Vivek's script runs fine, but I still cannot get a connection. Perhaps there is another step?
```
bspitzbart@ubuntu:~$ myproxy-logon -s myproxy.xsede.org -l bspitz
Enter MyProxy pass phrase:
Failed to receive credentials.
ERROR from myproxy-server:
PAM authentication failed: Permission denied
```

Can you add `-v` when you execute `myproxy-logon`? It seems like a password or ssh issue. Also you should use your XSEDE credentials

**Comment by iparask** [comment]
@bspitzbart anything new here?

**Comment by bspitzbart** [comment]
I am running Ubuntu 18.04 on my VMware virtual machine on Windows 10.
Get: Segmentation fault (core dumped)
The core dump mentions 'writing unknown VMA'
So, I am trying various combinations of VM players and OS. Any suggestions?

bspitzbart@ubuntu:~$ myproxy-logon -v -s myproxy.xsede.org -l bspitz -p 7512
MyProxy v6.1 May 2017 PAM SASL KRB5 LDAP VOMS OCSP
Attempting to connect to 141.142.149.142:7512 
Successfully connected to myproxy.xsede.org:7512 
using trusted certificates directory /etc/grid-security/certificates
no valid credentials found -- performing anonymous authentication
server name: /DC=org/DC=incommon/C=US/ST=IL/L=Urbana/O=University of Illinois/OU=NCSA/CN=myproxy.xsede.org
checking that server name is acceptable...
server name matches "myproxy.xsede.org"
authenticated server name is acceptable
Enter MyProxy pass phrase:
Segmentation fault (core dumped)

**Comment by bspitzbart** [comment]
I am running Ubuntu 18.04 on my VMware virtual machine on Windows 10.
Get: Segmentation fault (core dumped)
The core dump mentions 'writing unknown VMA'
So, I am trying various combinations of VM players and OS. Any suggestions?

bspitzbart@ubuntu:~$ myproxy-logon -v -s myproxy.xsede.org -l bspitz -p 7512
MyProxy v6.1 May 2017 PAM SASL KRB5 LDAP VOMS OCSP
Attempting to connect to 141.142.149.142:7512 
Successfully connected to myproxy.xsede.org:7512 
using trusted certificates directory /etc/grid-security/certificates
no valid credentials found -- performing anonymous authentication
server name: /DC=org/DC=incommon/C=US/ST=IL/L=Urbana/O=University of Illinois/OU=NCSA/CN=myproxy.xsede.org
checking that server name is acceptable...
server name matches "myproxy.xsede.org"
authenticated server name is acceptable
Enter MyProxy pass phrase:
Segmentation fault (core dumped)

**Comment by bspitzbart** [comment]
Eureka. Vivek's script works only with Ubuntu 16.04

**Comment by iparask** [comment]
It is Ubuntu 16 specific. Although you can change `xenial` to `bionic` and go with Ubuntu 18. Glad to hear that it worked!

**Comment by bspitzbart** [comment]
The script executed with bionic, but myproxy-logon gave the seg fault above. Anyway, I think this issue can be closed as it is being addressed with the README with instructions how to install and use EnTK pull request #22
