### ISSUE TITLE
predict_sealtnet.py does not create predicted_shapefiles

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#24]
I am using the `predict_sealnet.py` script that exists in devel. Specifically, this [one](https://github.com/iceberg-project/Seals/blob/devel/predict_sealnet.py). After executing it I found that it does not produce a folder named `WideResnetCount/predicted_shapefiles` as stated in issue #17.

The  command I am using is:
```
python3 "predict_sealnet.py" "--pipeline" "Pipeline1.1" "--dest_folder" "./" "--test_dir" "./" "--model_architecture" "WideResnetCount" "--hyperparameter_set" "A" "--model_name" "WideResnetCount"
```

In addition, I realized that it need a specific path structure to access the model, because the first time I run it, it produced the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '././/Pipeline1.1/WideResnetCount/WideResnetCount.tar'
```

My directory looks like this:
```
drwxr-xr-x  3 paraskev mc3bggp  22K Sep 14 14:24 Pipeline1.1
-rw-r--r--  1 paraskev mc3bggp 6.0K Sep 14 14:18 predict_sealnet.py
lrwxrwxrwx  1 paraskev mc3bggp  137 Aug 11 11:12 tiles -> /pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-157-203.jetstream-cloud.org.iparask.017749.0003/pilot.0000/unit.000000/tiles
drwxr-xr-x  5 paraskev mc3bggp  26K Aug 11 11:12 utils
-rw-r--r--  1 paraskev mc3bggp 524K Sep 14 14:36 WideResnetCount_predictions.csv
```

**Comment by iparask** [comment]
I would like to avoid predefined paths as much as possible. I suggest that the absolute path to the model provided to the script and not construct it during runtime.

Think of this code as a generic kernel. As long as the files necessary exist somewhere and we provide the paths to those, it should work.

**Comment by iparask** [comment]
ping @bentocg @bspitzbart  do you have any idea why this is happening?

**Comment by bentocg** [comment]
Oh, I see whats happening here, predict_sealnet only has a helper function that is called to predict patches in predict_raster_det. predict_raster_det combines all patch predictions into a shapefile.

**Comment by iparask** [comment]
Okay! So which file contains the correct kernel for the prediction? Also having a simple argument example will definitely help to import it in the pipeline scripts

**Comment by bentocg** [comment]
Giannis, predict_raster_det does the prediction on the whole scene and creates the shapefiles. I will have to add examples back from the jupyter notebooks, there is one example for valid arguments on the deploy_sealnet notebook. I added help messages on the argument parser too but they might not be too helpful.

**Comment by iparask** [comment]
I checked the example in [deploy_sealnet notebook](https://github.com/iceberg-project/Seals/blob/feature/19/deploy_sealnet.ipynb). As I understand tiling and prediction are happening in the `predict_raster_det` file, right? 

In order to be able to take advantage of EnTK's capabilities, we should separate the two basic kernels. From there if there is a need to use them sequentially, they can easily be imported and work as you want them to. Also, it will make notebook creation a bit easier, since your will import functions and you can use them as you want.

Does this make sense?

**Comment by bentocg** [comment]
Hi @iparask , it does. I am calling two helper functions that come from other scripts for prediction (predict_sealnet.py) and tiling (tile_raster.py). The helper function for subtiling is written in predict_raster_det, but there is no reason why we couldn't put it on a separate script. The only part that is really defined in predict_raster_det is the code to merge all patch predictions into a shapefile. Weren't we getting rid of notebooks? (maybe I'm confusing jupyter notebooks with EnTK)

**Comment by iparask** [comment]
Hello @bentocg, we are getting rid of notebooks. I will move this discussion to issue #34 and close this one, since that one is what is needed for getting the milestone. Is that okay with you?

**Comment by bentocg** [comment]
Hi @iparask , I use it all the time to run experiments, but it presupposes the old folder structure. I am in the middle of some final tests before submitting this for publication, you guys can go ahead and I'll try to adapt to the new structure once I'm done.

**Comment by iparask** [comment]
Hello @bentocg, please submit your publication and then we can move forward. That is perfectly understandable!

**Comment by iparask** [comment]
Fixed in devel
