### ISSUE TITLE
Folder organization in the repo

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#25]
I would like to suggest a new folder structure for this repo. I propose something like:

```
src -|
     | - EnTK script
     | - predicting
     | - tiling
     | - utils
models - | - Pipeline1
         | - Pipeline1.1
validation_suite -|
                  | - Pipeline1.1/data
                  | - Pipeline1/data
```

Any thoughts?

I think it will organise things a bit better and I will allow better structure.

**Comment by bspitzbart** [comment]
Maybe the above should be a deployment/predicting submodule?  Then we can keep all the code in the same repository but one can clone just the deployment code if that is all that is needed (like for the EnTK pipeline).  Of course, there are shared files like 'utils' to figure out where to put.  And updates get more complicated.  Just a thought.

**Comment by bspitzbart** [comment]
Add training and Pipeline1.2
src -|
     | - EnTK script
     | - training
     | - predicting
     | - tiling
     | - utils
models -|
         | - Pipeline1
         | - Pipeline1.1
         | - Pipeline1.2
validation_suite -| 
                  | - Pipeline1.2/data
                  | - Pipeline1.1/data
                  | - Pipeline1/data

**Comment by bspitzbart** [comment]
Actually, there is no code in 'models', so it is just 'src' and 'validation'

**Comment by iparask** [comment]
Yes, if that is the case.

**Comment by iparask** [comment]
I suggest the following: Let's finish merging pull request #28, #22 and me finish developing #27 and #26. At that point we freeze development for a couple of days until I create a PR that resolves this ticket. As soon as, that is merged with devel we can branch out again and continue development.

@bentocg , @bspitzbart do you agree?

**Comment by bentocg** [comment]
@iparask , sounds good!

**Comment by bspitzbart** [comment]
I added a new ticket #31 for removing imagery.  Can it be combined with this one?
