### ISSUE TITLE
RP examples *.prof error

### ISSUE THREAD

**Issue by bspitzbart** [iceberg-project/Seals#33]
Hi.  I think I have all the radical-pilot pieces working now, but try to run 00_getting_started.py and get  "cannot access '*.prof': No such file or directory"

Here is my setup and log files:
```
(/home/bspitzbart/entk_env) bspitzbart@ubuntu:~/RP_examples$ myproxy-logon -s myproxy.xsede.org -l bspitz
Enter MyProxy pass phrase:
A credential has been received for user bspitz in /tmp/x509up_u1000.
(/home/bspitzbart/entk_env) bspitzbart@ubuntu:~/RP_examples$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                 NAMES
a5dadf5bc3f6        rabbitmq:3          "docker-entrypoint.s…"   3 days ago          Up 3 days           0.0.0.0:32771->4369/tcp, 0.0.0.0:32770->5671/tcp, 0.0.0.0:32769->5672/tcp, 0.0.0.0:32768->25672/tcp   entk_queues2
(/home/bspitzbart/entk_env) bspitzbart@ubuntu:~/RP_examples$ export RADICAL_PILOT_DBURL=mongodb://radical-user:*******@ds121268.mlab.com:21268/radical-pilot
```
# execute example
(/home/bspitzbart/entk_env) bspitzbart@ubuntu:~/RP_examples$ python 00_getting_started.py &> verbose5.log

verbose5.log is empty,  rp.session.ubuntu.bspitzbart.017808.0000.log shows:
```
2018-10-04 14:07:04,570: rp.session.ubuntu.bspitzbart.017808.0000: MainProcess                     : MainThread     : ERROR   : failed to fet profile for pilot.0000
Traceback (most recent call last):
  File "/home/bspitzbart/entk_env/lib/python2.7/site-packages/radical/pilot/utils/session.py", line 168, in fetch_profiles
    profiles = sandbox.list('*.prof')
  File "/home/bspitzbart/entk_env/lib/python2.7/site-packages/saga/namespace/directory.py", line 243, in list
    return self._adaptor.list (pattern, flags, ttype=ttype)
  File "/home/bspitzbart/entk_env/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/bspitzbart/entk_env/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 473, in list
    % (ret, out))
NoSuccess: failed to list(): (2)(/bin/ls: cannot access '*.prof': No such file or directory
) (/home/bspitzbart/entk_env/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +473 (list)  :  % (ret, out)))
```

fetch-logfiles also fails:
```
(/home/bspitzbart/entk_env) bspitzbart@ubuntu:~/RP_examples/rp.session.ubuntu.bspitzbart.017808.0000$ radical-pilot-fetch-logfiles 17808
Traceback (most recent call last):
  File "/home/bspitzbart/entk_env/bin/radical-pilot-fetch-logfiles", line 88, in <module>
    rpu.fetch_logfiles(sid=sid, dburl=dburl, src=src, tgt=tgt, access=access, skip_existing=skip)
  File "/home/bspitzbart/entk_env/lib/python2.7/site-packages/radical/pilot/utils/session.py", line 254, in fetch_logfiles
    json_docs = get_session_docs(db, sid)
  File "/home/bspitzbart/entk_env/lib/python2.7/site-packages/radical/pilot/utils/db_utils.py", line 88, in get_session_docs
    raise ValueError ('no session %s in db (was `cleanup` disabled on `session.close()`?)' % sid)
ValueError: no session 17808 in db (was `cleanup` disabled on `session.close()`?)
```
```
(/home/bspitzbart/entk_env) bspitzbart@ubuntu:~/RP_examples/rp.session.ubuntu.bspitzbart.017808.0000$ radical-stack

  python               : 2.7.15
  pythonpath           : 
  virtualenv           : /home/bspitzbart/entk_env

  radical.entk         : 0.7.6
  radical.pilot        : 0.50.8
  radical.utils        : 0.50.2
  saga                 : 0.50.0
```

**Comment by iparask** [comment]
If I remember correctly you are using `conda python`? If yes can you please execute the example the following:
```
$: export RADICAL_PILOT_REPORT=TRUE
$: export RADICAL_PILOT_VERBOSE=DEBUG
$: python 00_getting_started.py local.localhost_anaconda
```

If not, can you verify that `python-dev` is installed? Is there a `radical.pilot.sandbox` folder under your home directory? If there is, does it contain anything?

**Comment by bspitzbart** [comment]
I did have to install python-dev and now get some output. It still seems to complain about *.prof, although there is pilot.0000.prof.tgz in the sandbox. Attached is the verbose output, logfile, and sandbox.
[rp.session.ubuntu.bspitzbart.017812.0007.log](https://github.com/iceberg-project/Seals/files/2457748/rp.session.ubuntu.bspitzbart.017812.0007.log)
[verbose.log](https://github.com/iceberg-project/Seals/files/2457749/verbose.log)
[rp.session.ubuntu.bspitzbart.017812.0007.tar.gz](https://github.com/iceberg-project/Seals/files/2457750/rp.session.ubuntu.bspitzbart.017812.0007.tar.gz)

**Comment by iparask** [comment]
Okay! It seems that something happens!

Can you please open the example file and in [line 92](https://github.com/radical-cybertools/radical.pilot/blob/master/examples/00_getting_started.py#L92) change `rp.MPI` to `rp.POSIX` and try again.

RADICAL-Pilot sees MPI units and your system does not have an MPI executor installed. As a result all the Compute Units fail. On the good news side, what you posted shows that RADICAL-Pilot works, but the units fail.

I will leave this ticket open until all requirements are satisfied.

**Comment by bspitzbart** [comment]
Looks like success.  I ran with POSIX and also installed MPI and the units
complete both ways.  There is just the red '- pilot.0000 (profiles)'. Is
that meaningful?

(/home/bspitzbart/entk_env) bspitzbart@ubuntu:~/RP_examples$ python
00_getting_started.py local.localhost_anaconda

================================================================================
 Getting Started (RP version
0.50.8)
================================================================================

new session:
[rp.session.ubuntu.bspitzbart.017814.0005]                        \
database   : [mongodb://
radical-user:radTest11@ds121268.mlab.com:21268/radical-pilot]
        ok
read
config                                                                   ok

--------------------------------------------------------------------------------
submit
pilots

create pilot
manager                                                          ok
submit 1 pilot(s)
        [local.localhost_anaconda:2]

ok

--------------------------------------------------------------------------------
submit
units

create unit
manager                                                           ok
add 1
pilot(s)                                                                ok
create 32 unit description(s)

................................                                      ok
submit 32 unit(s)

................................                                      ok

--------------------------------------------------------------------------------
gather
results

wait for 32 unit(s)

++++++++++++++++++++++++++++++++                                      ok

--------------------------------------------------------------------------------
finalize


closing session
rp.session.ubuntu.bspitzbart.017814.0005                       \
close unit
manager                                                            ok
close pilot
manager                                                            \
wait for 1 pilot(s)

timeout

ok
+ rp.session.ubuntu.bspitzbart.017814.0005 (json)
- pilot.0000 (profiles)
+ pilot.0000 (logfiles)
session lifetime:
23.2s                                                       ok

--------------------------------------------------------------------------------

**Comment by iparask** [comment]
That is perfectly fine. It means that there were no profiles to download and that is right since we did not ask RADICAL-Pilot to generate any profile. I consider this ticket resolved. Is it okay if we close it?

**Comment by bspitzbart** [comment]
Just add a caveat that the myproxy instructions are only tested under
Ubuntu 16.04 and it is good to go.

**Comment by iparask** [comment]
Okay!
