### ISSUE TITLE
Assemble and transfer full dataset to Bridges

### ISSUE THREAD

**Issue by bspitzbart** [iceberg-project/Seals#39]

**Comment by iparask** [comment]
This issue blocks the milestone. It is also blocked by [ICEBERG Administration issue 15](https://github.com/iceberg-project/ICEBERG-administration/issues/15)

**Comment by bspitzbart** [comment]
Get Globus endpoint on SeaWulf

**Comment by iparask** [comment]
Brad, can you verify the data size of the whole dataset? 

Based on the TXT file you provided me the size is 5TBs. I may very well make some kind of mistake, but I would like to avoid asking for space that we will not utilize, because that would reduce our credibility for later.

Thank you,
Giannis

**Comment by bspitzbart** [comment]
Hi Giannis,
  Which txt file? In any case, the Seals data we have for last season is 12
TB, and it would be easy to run more.

**Comment by iparask** [comment]
You gave at some point a txt file, called `2017seals_list`, that has all the images and their size. I mean that one.

Thank you for verifying.
