### ISSUE TITLE
Very large number of files in master

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#4]
Hello,

I am trying to clone the merged versions so that I can continue working on issue #1 . Although having 257k files on a repo that is also used for development makes cloning and branching a bit difficult. There are two basic and significant effects:
1. We will commit that number of files every time a new branch is created that develops a new feature or tests a new script.
2. The repo's size is becoming very large and we already are above the recommended [limit](https://help.github.com/articles/what-is-my-disk-quota/#file-and-repository-size-limitations). I do not object to use versioning for data, if it is needed, but I am not sure whether or not Github is the correct solution.

I suggest that the master branch is cleaned from all the image files and any file/folder that is either hidden, i.e. prefix `.`, or produced by Python3 interpreter, `__pycache__`.

A web server or common folders on Bridges can provide for data sharing.

**Comment by iparask** [comment]
I think, there is a way to delete something [completely](https://help.github.com/articles/removing-files-from-a-repository-s-history/) from Github, along with its history. I do further checks and report again.

**Comment by bspitzbart** [comment]
I removed the test_scenes folder, which was most of the files, and a few smaller things.  There is a pull request issued if you want to review how it will merge with master. Thanks.

**Comment by bspitzbart** [comment]
test_scenes folder removed from all branches and temporary branches, saved_models and cleaned, are merged with master and removed.
