### ISSUE TITLE
Image format not recongized

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#45]
Hello Brad,

I got this error:
```
rasterio._err.CPLE_OpenFailed: 'WV03_20170930021148_1040010033C12500_17SEP30021148-P1BS-501946346030_01_P003_u08rf3031.tif' not recognised as a supported file format.
```
I think this image file is corrupt. Can you re-upload it?

**Comment by bspitzbart** [comment]
There is indeed something wrong with the original file, so we can skip that one for now.

**Comment by iparask** [comment]
I see, I will keep it open for a couple of days until I finish some more runs

**Comment by iparask** [comment]
Closing this one.
