### ISSUE TITLE
Tiling script does not generate correct Affine matrix

### ISSUE THREAD

**Issue by bentocg** [iceberg-project/Seals#46]
'tile_raster.py' is using the 'affine' package to generate an affine matrix but 'predict_sealnet.py' expects affine matrices from the 'rasterio' package.

**Comment by iparask** [comment]
Initially, the EnTK script needs to setup `PYTHONPATH` to the virtual env to get the correct version of `rasterio`.

And `predict_sealnet.py` should get as input the image name.

**Comment by iparask** [comment]
Closing since PR #48 was merged
