### ISSUE TITLE
default predict params

### ISSUE THREAD

**Issue by bspitzbart** [iceberg-project/Seals#5]
These are the simple default params we can use to start:

python predict_raster.py --input_image=$img_path \
                                  --class_architecture='Densenet169' --count_architecture='WideResnetCount' \
                                  --hyperparameter_set_class='B' --hyperparameter_set_count='A' \
                                  --training_dir='training_set_vanilla' --dest_folder=$out_fldr \
                                  --pos_classes='crabeater_weddell'

There are some hard-coded paths and dependencies I need to look into and document.

**Comment by iparask** [comment]
Okay! Thank you! This is allows development based on Issue #1  to continue

**Comment by bspitzbart** [comment]
And there are 17 images available at /pylon5/mc3bggp/bspitz
The permissions should be fixed.

**Comment by iparask** [comment]
There are! Thank you!

**Comment by iparask** [comment]
I am getting this error:
```
(pytorchCuda) [paraskev@gpu047 Seals]$ python predict_raster.py --input_image=/pylon5/mc3bggp/bspitz/WV03_20180109041355_1040010037D5E000_18JAN09041355-P1BS-501954062030_01_P007_u08rf3031.tif --class_architecture='Densenet169' --count_architecture='WideResnetCount' --hyperparameter_set_class='B' --hyperparameter_set_count='A' --training_dir='training_set_vanilla' --dest_folder=test --pos_classes='crabeater_weddell'

40694 tiles created in 3 minutes and 8.79 seconds

Predicting with test:
predict_raster.py:219: FutureWarning: The value of this property will change in version 1.0. Please see https://github.com/mapbox/rasterio/issues/86 for details.
  main()
Traceback (most recent call last):
  File "predict_raster.py", line 219, in <module>
    main()
  File "predict_raster.py", line 120, in main
    class_names = sorted([subdir for subdir in os.listdir('./training_sets/{}/training'.format(args.training_dir))])
FileNotFoundError: [Errno 2] No such file or directory: './training_sets/training_set_vanilla/training'
```
I am missing the `training_set_vanilla` folder. Can you point me to a path?

**Comment by bentocg** [comment]
Hi Giannis,
You can solve that by hardwiring class_names to sorted(['crabeater',
'weddell', 'pack-ice', 'open-water', 'ice-sheet', 'emperor',
'marching-emperor', 'crack', 'rock', 'other']). I had it searching the
training directory to look for class names but we don't need that for
production.

Bento

2018-06-18 22:56 GMT+02:00 Ioannis Paraskevakos <notifications@github.com>:

**Comment by bspitzbart** [comment]
I will also need to send you the actual trained models, which are not in the repo, and the expected directory structure.  I should have it tomorrow.

**Comment by bspitzbart** [comment]
@iparask I sent you a link to the model weight files on google drive.  Here is the expected directory structure where predict_sealnet.py will look for them:

predict_sealnet.py line 140 
# load saved model weights from pt_train.py
    model_ft.load_state_dict(torch.load("./{}/{}/{}/{}.tar".format(args.dest_folder, args.pipeline, args.model_name,args.model_name)))

**Comment by bentocg** [comment]
@bspitzbart  and @iparask 
There are only a couple of model weight files that pass the size limit and they don't even perform well, maybe you can remove .tar from the .gitignore, get rid of the big models and push the repo again (I would guess its VGG16 and Resnet50 inside 'saved_models_stable/Pipeline1' but you can check). This would also fix the directory problem and might be a bit more convenient.

**Comment by iparask** [comment]
I am closing this issue because it has been resolved
