### ISSUE TITLE
Package this repo to be installable

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#54]
The Seals use case will be packaged and provided via pip.

**Comment by iparask** [comment]
Hello @hlynch, @bentocg, and @bspitzbart 

Seals will become an installable package from pipy! This will allow users to do:
```bash
pip install name
```

and install it.

The most important part is how to name it. I have in my mind something like `iceberg.seals` but I would like also your opinion! Feel free to let me know!

**Comment by hlynch** [comment]
My only concern is that people may, many years hence, think this is looking for seals on icebergs. Do we have other names decided on that take a format we should follow? I wonder if we could call it seal.search?

**Comment by bspitzbart** [comment]
Heather makes a good point that iceberg could be confusing and the same
will apply to the other use cases (iceberg.rivers?). But we also want to
keep the standalone installation connected to the larger iceberg "brand".
Maybe iceberg_ci.seals? Then users will be tipped off to find out the
significance of "_ci" if they are unfamiliar.

**Comment by hlynch** [comment]
How about: iceberg_seal.search, iceberg_river.mapping, iceberg_landcover.classification,iceberg_penguin.guano etc.,

**Comment by iparask** [comment]
I'll use `iceberg_seal.search` for now and we can change it later if we want!
