### ISSUE TITLE
Num_workers in DataLoader

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Seals#7]
Hello @bentocg , I am not sure what the `num_workers` mean [here](https://github.com/iceberg-project/Seals/blob/devel/predict_sealnet.py#L60). Does it require that number of CPU cores to execute?

**Comment by bentocg** [comment]
Hi Giannis, 'num_workers' here means the number of parallel processes running on the GPU. Note that it is separating the processes at the batch level, so batch size has to be divisible by num_workers.

**Comment by iparask** [comment]
So the task needs multiple CPU cores to be executed correctly! Will fix and commit.

**Comment by bentocg** [comment]
Not sure, I've used more workers then the available CPU cores before. It loads the whole batch of images and the tensors in the GPU memory.

**Comment by iparask** [comment]
Closing because it is not updated recently
